namespace: weather-prod

image:
  repository: docker.io/temmaw/weather-app
  tag: "1.0.1"
  pullPolicy: IfNotPresent

database:
  enabled: true
  url: postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@my-release-postgresql.default.svc.cluster.local:5432/postgres

ingress:
  enabled: true
  host: weather.example.com

persistence:
  size: 10Gi

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
