{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-app-pv
  namespace: weather
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/weather
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
# PersistentVolumeClaim
  name: {{ .Values.app.name }}-pvc 
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
