{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: weather-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
